Dockerfile.dbg
Dockerfile.in
Makefile
cmd/stash-percona-xtradb/version.go
hack/build.sh
hack/docker/stash-percona-xtradb/backup.sh
hack/docker/stash-percona-xtradb/restore.sh
hack/e2e.sh
hack/license/bash.txt
hack/license/dockerfile.txt
hack/license/go.txt
hack/license/makefile.txt
hack/test.sh
pkg/backup.go
pkg/restore.go
pkg/root.go
pkg/utils.go

Add license header to files

---

docs/clustered.md

fixes: https://github.com/stashed/stash/issues/962

Add scheme field in AppBinding yaml

---

.github/workflows/cherry-pick.yml
hack/scripts/cherry-pick.sh

[cherry-pick] Add workflow to cherry pick commits to master (#23)

---

.github/workflows/release-tracker.yml
hack/scripts/cherry-pick.sh
hack/scripts/update-release-tracker.sh

[cherry-pick] Add script to update release tracker on pr merge (#25)

---

.github/workflows/release.yml
hack/scripts/cherry-pick.sh

[cherry-pick] Update release.yml

---

Makefile
charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
lintconf.yaml

Add commands to update chart version

---

.github/workflows/release.yml

[cherry-pick] Publish to testing dir for alpha/beta releases (#32)

---

.github/workflows/release.yml

[cherry-pick] Build docker image in release workflow (#36)

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
go.mod
go.sum
vendor/modules.txt

Prepare for release v2020.07.09-beta.0

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
go.mod
go.sum
vendor/modules.txt

Release: v2020.07.09-beta.0
Release-tracker: https://github.com/stashed/CHANGELOG/pull/2

Prepare for release 5.7-beta.20200709

---

Makefile

[cherry-pick] Make chart registry configurable (#40)

---

charts/stash-percona-xtradb/Chart.yaml

[cherry-pick] Update chart icon

---

Makefile

Signed-off-by: hossainemruz <emruz@appscode.com>

Make image.tag in values.yaml file as same as $APP_VERSION

---

Makefile

Signed-off-by: hossainemruz <emruz@appscode.com>

[cherry-pick] Make image.tag in values.yaml file as same as $APP_VERSION (#44)

---

docs/clustered.md
docs/percona-xtradb.md

Signed-off-by: Emruz Hossain <emruz@appscode.com>

Update Stash installation link

---

docs/clustered.md
docs/percona-xtradb.md

Signed-off-by: Emruz Hossain <emruz@appscode.com>

[cherry-pick] Update Stash installation link (#47)

---

README.md

[cherry-pick] Update issues link

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
charts/stash-percona-xtradb/values.yaml
go.mod
go.sum
vendor/modules.txt

Release: v2020.08.26-rc.1
Release-tracker: https://github.com/stashed/CHANGELOG/pull/5

Prepare for release 5.7-rc.20200826

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
charts/stash-percona-xtradb/values.yaml
go.mod
go.sum
vendor/modules.txt

Prepare for release v2020.08.26-rc.1

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
charts/stash-percona-xtradb/values.yaml
go.mod
go.sum
vendor/modules.txt

Prepare for release v2020.08.27-rc.0

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
charts/stash-percona-xtradb/values.yaml
go.mod
go.sum
vendor/modules.txt

Release: v2020.08.27-rc.0
Release-tracker: https://github.com/stashed/CHANGELOG/pull/6

Prepare for release 5.7-rc.20200827

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
charts/stash-percona-xtradb/values.yaml
go.mod
go.sum
vendor/modules.txt

Release: v2020.08.27
Release-tracker: https://github.com/stashed/CHANGELOG/pull/7

Prepare for release 5.7-v1

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
charts/stash-percona-xtradb/values.yaml
go.mod
go.sum
vendor/modules.txt

Prepare for release v2020.08.27

---

Makefile
docs/clustered.md
docs/percona-xtradb.md

Update task names from Makefile

---

Makefile
docs/clustered.md
docs/percona-xtradb.md

[cherry-pick] Update task names from Makefile (#67)

---

.github/workflows/ci.yml
Makefile

[cherry-pick] Update repository config (#69)

---

Makefile

[cherry-pick] Update repository config (#71)

---

go.mod
go.sum
vendor/kmodules.xyz/client-go/api/v1/conditions.go
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#75)

---

hack/kubernetes/kind.yaml
hack/kubernetes/storageclass/standard.yaml

[cherry-pick] Update repository config (#77)

---

go.mod
go.sum
vendor/kmodules.xyz/custom-resources/apis/appcatalog/v1alpha1/appbinding_helpers.go
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#79)

---

.github/workflows/release.yml
Dockerfile.dbg
Dockerfile.in

[cherry-pick] Publish docker images to ghcr.io (#81)

---

go.mod
go.sum
vendor/kmodules.xyz/client-go/meta/annotations.go
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#83)

---

.github/workflows/ci.yml

[cherry-pick] Update repository config (#86)

---

hack/kubernetes/kind.yaml

[cherry-pick] Update repository config (#88)

---

go.mod
go.sum
vendor/kmodules.xyz/client-go/meta/hash.go
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#91)

---

go.mod
go.sum
vendor/kmodules.xyz/client-go/api/v1/conditions.go
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#93)

---

Makefile

[cherry-pick] Use restic 0.11.0 (#108)

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
charts/stash-percona-xtradb/values.yaml
docs/examples/clustered/backup/backupconfiguration.yaml
docs/examples/clustered/restore/restoresession.yaml
docs/examples/standalone/backup/backupconfiguration.yaml
docs/examples/standalone/restore/restoresession.yaml
go.mod
go.sum
vendor/modules.txt

Prepare for release v2020.11.06

---

go.mod
go.sum
vendor/go.bytebuilders.dev/license-verifier/go.mod
vendor/go.bytebuilders.dev/license-verifier/go.sum
vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.mod
vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.sum
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#114)

---

.github/workflows/ci.yml

[cherry-pick] Update repository config (#116)

---

go.mod
go.sum
vendor/kmodules.xyz/client-go/core/v1/kubernetes.go
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#123)

---

pkg/backup.go
pkg/restore.go

Signed-off-by: Emruz Hossain <emruz@appscode.com>
Ref: stashed/stash#1272

[cherry-pick] Use port from AppBinding (#120)

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
charts/stash-percona-xtradb/values.yaml
docs/examples/clustered/backup/backupconfiguration.yaml
docs/examples/clustered/restore/restoresession.yaml
docs/examples/standalone/backup/backupconfiguration.yaml
docs/examples/standalone/restore/restoresession.yaml
go.mod
go.sum
vendor/modules.txt
vendor/stash.appscode.dev/apimachinery/apis/repositories/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/stash/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/stash/v1beta1/openapi_generated.go

Release: v2020.12.17
Release-tracker: https://github.com/stashed/CHANGELOG/pull/25

Prepare for release 5.7.0-v1

---

charts/stash-percona-xtradb/Chart.yaml
charts/stash-percona-xtradb/README.md
charts/stash-percona-xtradb/doc.yaml
charts/stash-percona-xtradb/values.yaml
docs/examples/clustered/backup/backupconfiguration.yaml
docs/examples/clustered/restore/restoresession.yaml
docs/examples/standalone/backup/backupconfiguration.yaml
docs/examples/standalone/restore/restoresession.yaml
go.mod
go.sum
vendor/modules.txt
vendor/stash.appscode.dev/apimachinery/apis/repositories/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/stash/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/stash/v1beta1/openapi_generated.go

Prepare for release v2020.12.17

---

go.mod
go.sum
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#128)

---

go.mod
go.sum
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#130)

---

go.mod
go.sum
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#132)

---

.github/workflows/ci.yml
.github/workflows/release.yml

[cherry-pick] Update repository config (#134)

---

go.mod
go.sum
vendor/go.bytebuilders.dev/license-verifier/kubernetes/Makefile
vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.mod
vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.sum
vendor/go.bytebuilders.dev/license-verifier/lib.go
vendor/kmodules.xyz/client-go/core/v1/pod.go
vendor/kmodules.xyz/client-go/core/v1/pod_status.go
vendor/kmodules.xyz/client-go/go.mod
vendor/kmodules.xyz/client-go/go.sum
vendor/kmodules.xyz/client-go/meta/dataformat.go
vendor/modules.txt

[cherry-pick] Update Kubernetes v1.18.9 dependencies (#137)

---

hack/kubernetes/kind.yaml

[cherry-pick] Update repository config (#139)

---

.github/workflows/ci.yml

[cherry-pick] Update repository config (#141)

---

charts/stash-percona-xtradb/README.md
go.mod
go.sum
vendor/modules.txt

Update Kubernetes v1.18.9 dependencies

---

.github/workflows/ci.yml

[cherry-pick] Check codespan schema (#146)

---

Makefile
pkg/root.go

[cherry-pick] Use restic 0.12.0 (#150)

---

Makefile

[cherry-pick] Update repository config (#159)

---

README.md

[cherry-pick] Fix spelling

---

Dockerfile.dbg
Dockerfile.in
Makefile

[cherry-pick] Use restic v0.12.0-ac.20210727 (#186)

---

Dockerfile.dbg
Dockerfile.in

[cherry-pick] Update repository config (#191)

---

Dockerfile.dbg
Dockerfile.in

[cherry-pick] Update repository config (#196)

---

Dockerfile.in

[cherry-pick] Update repository config (#198)

---

.github/workflows/ci.yml
Makefile

[cherry-pick] Update repository config (#207)

---

go.mod
go.sum
vendor/modules.txt

[cherry-pick] Log warning if Community License is used with non-demo namespace (#211)

---

go.mod
go.sum
vendor/modules.txt

[cherry-pick] Fix jwt-go security vulnerability (#219)

---

go.mod
go.sum
vendor/go.bytebuilders.dev/license-verifier/Makefile
vendor/go.bytebuilders.dev/license-verifier/info/lib.go
vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.mod
vendor/go.bytebuilders.dev/license-verifier/kubernetes/lib.go
vendor/go.bytebuilders.dev/license-verifier/lib.go
vendor/modules.txt

[cherry-pick] Update dependencies (#226)

---

go.mod
go.sum
vendor/go.bytebuilders.dev/license-verifier/info/lib.go
vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.mod
vendor/go.bytebuilders.dev/license-verifier/kubernetes/lib.go
vendor/go.bytebuilders.dev/license-verifier/lib.go
vendor/modules.txt

[cherry-pick] Fix SiteInfo publishing (#228)

---

go.mod
go.sum
vendor/modules.txt

Prepare for release v2021.11.24

---

pkg/root.go

[cherry-pick] make fmt (#240)

---

.github/workflows/ci.yml
Makefile

[cherry-pick] Use Go 1.18 (#242)

---

Makefile
go.mod
go.sum
vendor/kmodules.xyz/client-go/api/v1/timeofday.go
vendor/kmodules.xyz/client-go/meta/incluster.go
vendor/modules.txt

[cherry-pick] Use restic 0.13.1 (#250)

---

pkg/backup.go
pkg/restore.go
pkg/utils.go

* Make sure to fail the backup/restore sessions if license check fails.
Signed-off-by: piyush1146115 <piyush@appscode.com>
* Refactor implementation.
Signed-off-by: piyush1146115 <piyush@appscode.com>

[cherry-pick] Make sure to fail the backup/restore sessions if license check fails. (#258)

---

Makefile

[cherry-pick] Use restic 0.14.0 (#268)

---

Makefile

[cherry-pick] Revert to restic 0.13.1 (#270)

---

.github/workflows/cherry-pick.yml
.github/workflows/ci.yml
.github/workflows/release-tracker.yml
.github/workflows/release.yml
Dockerfile.dbg
Dockerfile.in
Makefile

Run GH actions on ubuntu-20.04

---

.github/workflows/cherry-pick.yml
.github/workflows/ci.yml
.github/workflows/release-tracker.yml
.github/workflows/release.yml
Dockerfile.dbg
Dockerfile.in
Makefile

* Run GH actions on ubuntu-20.04
* Fix docker build
Co-authored-by: Tamal Saha <tamal@appscode.com>

[cherry-pick] Run GH actions on ubuntu-20.04 (#274)

---

.github/workflows/ci.yml
Makefile
go.mod
go.sum
vendor/golang.org/x/crypto/AUTHORS
vendor/golang.org/x/crypto/CONTRIBUTORS
vendor/golang.org/x/crypto/pkcs12/crypto.go
vendor/golang.org/x/crypto/pkcs12/internal/rc2/rc2.go
vendor/modules.txt

[cherry-pick] Update workflows (Go 1.20, k8s 1.26) (#282)

---

go.mod
go.sum
vendor/modules.txt
vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go

Release: v2023.03.13
Release-tracker: https://github.com/stashed/CHANGELOG/pull/63

Prepare for release 5.7-v18

---

Dockerfile.in

[cherry-pick] Use numeric uid in Dockerfile (#288)

---

go.mod
go.sum
vendor/modules.txt
vendor/stash.appscode.dev/apimachinery/apis/repositories/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/stash/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/stash/v1beta1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/ui/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go
vendor/stash.appscode.dev/apimachinery/pkg/restic/restore.go

Release: v2023.04.30
Release-tracker: https://github.com/stashed/CHANGELOG/pull/65

Prepare for release 5.7-v20

---

go.mod
go.sum
vendor/go.bytebuilders.dev/license-verifier/Makefile
vendor/go.bytebuilders.dev/license-verifier/info/lib.go
vendor/go.bytebuilders.dev/license-verifier/kubernetes/Makefile
vendor/go.bytebuilders.dev/license-verifier/kubernetes/lib.go
vendor/modules.txt

[cherry-pick] Update license verifier (#294)

---

.github/workflows/cherry-pick.yml
.github/workflows/ci.yml
.github/workflows/release-tracker.yml
.github/workflows/release.yml
Makefile

Use Go 1.23 (#321)

---

Makefile

[cherry-pick] Use debian:12 base image (#325)

---

Dockerfile.dbg
Dockerfile.in

[cherry-pick] Use debian:12 base image (#327)

---

Makefile
go.mod
go.sum
vendor/modules.txt
vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go
vendor/stash.appscode.dev/apimachinery/pkg/restic/config.go
vendor/stash.appscode.dev/apimachinery/pkg/restic/migrate.go

Signed-off-by: Md. Ishtiaq Islam <ishtiaq@appscode.com>

[cherry-pick] Update restic version (#335)

---

.github/workflows/ci.yml
.github/workflows/release.yml

[cherry-pick] Disable image caching in setup-qemu action (#337)

---

Dockerfile.in
hack/docker/stash-percona-xtradb/restore.sh
pkg/backup.go
pkg/restore.go

Signed-off-by: SK Ali Arman <arman@appscode.com>

Update garbd version to 80

---

.github/workflows/ci.yml
Makefile

[cherry-pick] Use Go 1.24 (#342)

---

.github/workflows/ci.yml
Makefile

[cherry-pick] Use Go 1.25 (#354)
